### ISSUE TITLE
Improve the loading UX on a project page

### ISSUE THREAD

**Issue by schwepps** [Carbonable/contracts-watcher#26]
**Description**
---
Improve the loading experience with better loaders and placeholders on the project page.

**Acceptance Criteria**
---

- [ ] When all the data from the slot uri are loading, add placeholders to improve the user experience.

**Comment by Shoetan** [comment]
Can I jump on this task? I am a returning contributor to this project 
Past PR: https://github.com/carbonable-labs/carbon-protocol-v3/pull/82

**Comment by starknetbrother** [comment]
I'm a first time contributor and would love to work on this

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by josephpdf** [comment]
Hi! @schwepps
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Analyze Current Loading Behavior:** Review the current implementation of the project page to identify where loaders or placeholders are missing.
2. **Design Effective Placeholders:** Create lightweight, visually appealing placeholders that match the project's design style to display while data loads.
3. **Improve Loader Functionality:** Add loading indicators for key data-fetching points using methods like React's `Suspense`, CSS animations, or progress bars.
4. **Test Enhancements:** Simulate slow network conditions to test the new loaders and placeholders, ensuring they enhance user experience.

**Comment by julienbrs** [comment]
Issue has been assigned to @Shoetan as he was the first one to ask. Other issues are ready to get picked up!
